[package]
name = "oteepee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base32 = "0.4.0"
sha1 = "0.10.1"
sha2 = "0.10.2"
hmac = "0.12.1"
